baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "The Wall"
theme = 'ed'
enableRobotsTXT = true
refLinksErrorLevel = 'WARNING'
[params]
  description = ''
  mainSections = ['posts', 'dramas', 'narratives', 'poems']
  colorScheme = 'red'
  readmore = true
  recentPostsSize = 5
  tagline = "Surely I'm Joking"
  dateFormat = ':date_long'
  dateFormatToc = '2006.01.02'
  footer = 'Built with <a href="https://github.com/sergeyklay/gohugo-theme-ed" target="_blank" rel="noopener noreferrer">Ed</a>. Distributed under an MIT license.'

  showAuthor = false
  [params.author]
    name = 'spp'
    email = 'sun.april.moon at gmail.com'
    location = 'nowhere'


  [params.privacy]
    [params.privacy.googleTagManager]
      disable = true
      respectDoNotTrack = true
  # [params.search]
  #   maxSummaryLength = 100
  #   languages = ['en']

[languages]
  [languages.en]
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1

[menus]
  [[menus.main]]        # sections in the website sidebar
    identifier = 'home' # menu item id
    name = 'Home'       # menu item display title
    pageRef = '/'       # path to the page
    weight = 1          # order of the menu item
  [[menus.main]]
    identifier = 'about'
    name = 'About'
    pageRef = '/about'
    weight = 2
  # [[menus.main]]
  #   identifier = 'credits'
  #   name = 'Credits'
  #   pageRef = '/credits'
  #   weight = 3
  # [[menus.main]]
  #   identifier = 'documentation'
  #   name = 'Documentation'
  #   pageRef = '/documentation'
  #   weight = 4
  # [[menus.main]]
  #   identifier = 'search'
  #   name = 'Search'
  #   pageRef = '/search'
  #   weight = 5
  # [[menus.main]]
  #   identifier = 'contact'
  #   name = 'Contact'
  #   pageRef = '/contact'
  #   weight = 6
  # [[menus.main]]
  #   identifier = 'github'
  #   name = 'GitHub Project'
  #   url = 'https://github.com/sergeyklay/gohugo-theme-ed/'
  #   weight = 20
  #   params = {external = true}

  [[menus.feeds]]
    identifier = 'rss'
    name = 'RSS 2.0'
    url = '/rss.xml'
    weight = 1
  [[menus.feeds]]
    identifier = 'atom'
    name = 'Atom'
    url = '/atom.xml'
    weight = 2
  [[menus.feeds]]
    identifier = 'json'
    name = 'Json Feed'
    url = '/feed.json'
    weight = 3

[pagination]
  pagerSize = 10

[taxonomies]
  tag = 'tags'
  category = 'categories'


[outputs]
  home = ['html', 'rss', 'manifest', 'atom', 'jsonfeed', 'json', 'humanstxt']
  page= ['html']
  rss = ['rss']
  section = ['html', 'rss', 'atom', 'jsonfeed']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

[outputFormats]
  # For more see: https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  [outputFormats.atom]
    name = 'atom'
    # The correct header Content-Type header for an Atom feed is
    # application/atom+xml. However, Chromium does not handle it
    # correctly (see https://code.google.com/p/chromium/issues/detail?id=104358).
    #
    # The most compatible header is 'text/xml; charset=utf-8', which
    # will cause the feed to be parsed correctly by most clients.
    # Note that you should be encoding your feed in UTF-8.
    mediaType = 'text/xml'
    # generated file = <baseName>.<mediaType.'text/xml'.suffixes[0]> = atom.xml
    baseName = 'atom'
    rel = 'alternate'
    isPlainText = false
    isHTML = false
    noUgly = true

  # For more see: https://www.jsonfeed.org/
  [outputFormats.jsonfeed]
    name = 'jsonfeed'
    mediaType = 'application/feed+json'
    baseName = 'feed'
    rel = 'alternate'
    isPlainText = true
    isHTML = false
    noUgly = false

  [outputFormats.manifest]
    # The .webmanifest extension is specified in the Media type registration
    # section of the specification (the response of the manifest file should
    # return Content-Type: application/manifest+json).
    #
    # For more see: https://w3c.github.io/manifest/#media-type-registration=
    name = 'manifest'
    mediaType = 'application/manifest+json'
    baseName = 'manifest'
    rel = 'manifest'
    isPlainText = true
    isHTML = false
    noUgly = false
    notAlternative = false

  # For more see: https://gohugo.io/templates/output-formats/
  [outputFormats.humanstxt]
    name = 'humanstxt'
    mediaType = 'text/plain'
    baseName = 'humans'
    rel = 'author'
    isPlainText = true
    isHTML = false
    noUgly = true
    notAlternative = true

  [outputFormats.rss]
    baseName = 'rss'
    mediaType = 'application/rss+xml'


[mediaTypes]
  [mediaTypes.'text/xml']
    suffixes = ['xml']
  [mediaTypes.'application/feed+json']
    suffixes = ['json']

[module]
  [[module.imports]]
    path = 'github.com/MihaiValentin/lunr-languages'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    # false due to generated Syntax Highlighter CSS
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        # Enable custom attribute support for blocks
        block = true


[frontmatter]
  lastmod = ['lastmod', ':git', 'modified', 'date', 'publishdate', 'pubdate', 'published']


[minify]
  # Do not minify XML files to avoid CDATA escape issues
  disableXML = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepQuotes = true
